In [14]:
import torch
a = torch.tensor([2.0], requires_grad=True)
b = torch.tensor([4.0], requires_grad=True)
c = torch.tensor([1.0], requires_grad=True)
d = torch.tensor([5.0], requires_grad=False)

print(a.grad)
print(b.grad)
print(c.grad)
print(d.grad)

def show_tensor_params(*tensors):
  for x in tensors:
    print('---')
    print(f"data - {x.data}")
    print(f"grad - {x.grad}")
    print(f"grad_fn - {x.grad_fn}")
    print(f"req_grad - {x.requires_grad}")
    print(f"is_leaf - {x.is_leaf}")

s = (a,b,c,d)
for x in s:
  print (show_tensor_params(x))

None
None
None
None
---
data - tensor([2.])
grad - None
grad_fn - None
req_grad - True
is_leaf - True
None
---
data - tensor([4.])
grad - None
grad_fn - None
req_grad - True
is_leaf - True
None
---
data - tensor([1.])
grad - None
grad_fn - None
req_grad - True
is_leaf - True
None
---
data - tensor([5.])
grad - None
grad_fn - None
req_grad - False
is_leaf - True
None


In [15]:
loss = a*b + c*d
loss.backward()
for x in s:
    print(x.grad)
print (loss)

tensor([4.])
tensor([2.])
tensor([5.])
None
tensor([13.], grad_fn=<AddBackward0>)
