1.3.1 Задание
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.

In [83]:
import numpy as np
#Решение
x=np.ones((8,8)).astype(int)
for i in range(0,8,2):
    for j in range(0,8,2):
        x[i][j] = 0
        x[i+1][j+1] = 0
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1.3.2 Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arange

In [44]:
import numpy as np
#Решение
x = np.arange(25).reshape(5,5)
for i in range (1,5):
    for j in range(5):
        x[i][j] = x[0][j] 
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3 Задание
Создать массив 3x3x3 со случайными значениями.

In [47]:
import numpy as np
#Решение
x = np.random.random((3,3,3))
print(x)

[[[0.93518537 0.16575262 0.33007615]
  [0.67356062 0.20877072 0.12552696]
  [0.46356806 0.0114028  0.42765758]]

 [[0.20598641 0.86080051 0.42746161]
  [0.7928761  0.60404995 0.98796395]
  [0.81579903 0.15189326 0.91454856]]

 [[0.45893091 0.57360729 0.5477029 ]
  [0.50783682 0.79865582 0.67011545]
  [0.92052156 0.65966446 0.75757911]]]


1.3.4 Задание
Создать матрицу с 0 внутри, и 1 на границах.


In [49]:
import numpy as np
#Решение
n=int(input("Введите количество строк: "))
m=int(input("Введите количество столбцов: "))
x = np.ones((n,m)).astype(int)
for i in range(1, n-1):
    for j in range(1,m-1):
        x[i][j]=0
print(x)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


1.3.5 Задание
Создайте массив и отсортируйте его по убыванию.

In [65]:
import numpy as np
#Решение
rng = np.random.default_rng()
n=int(input("Введите количество элементов массива: "))
x = rng.integers(low =0, high =100, size = n)
x=(np.sort(x))
x=x[::-1]
print(x)

[98 96 93 90 89 88 88 84 78 77 70 68 66 66 64 63 63 62 62 61 60 59 55 54
 54 49 49 45 43 43 39 38 36 36 35 35 34 30 29 29 29 29 27 26 22 22 18 15
 14  9  6  4  3  2  1  0]


1.3.6 Задание
Создайте матрицу, выведите ее форму, размер и размерность.

In [4]:
import numpy as np
#Решение
rng = np.random.default_rng()
n=int(input("Введите количество строк: "))
m=int(input("Введите количество столбцов: "))
x=rng.integers(low =0, high =100, size=(n,m))
print(x)
print("Форма: ",x.shape)
print("Размер: ",x.size)
print("Размерность: ",x.ndim)


[[16 70 83 ... 59 39 18]
 [23 52 72 ... 21 95  8]
 [69 54 86 ...  3 76 34]
 ...
 [78 72 77 ... 12 81 66]
 [93 33 90 ... 44 29 52]
 [71 12 49 ... 82 22  6]]
Форма:  (32, 34)
Размер:  1088
Размерность:  2


2.3.1 Задание
Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.


In [3]:
#Решение
import pandas as pd
import numpy as np
rng = np.random.default_rng()
n=int(input("Введите значение размерности пространства точек: "))
x = rng.integers(low =0, high =100, size=(n))
x1 = pd.Series(x)
y = rng.integers(low =0, high =100, size=(n))
y1 = pd.Series(y)
sum=0
print("Точка а: ", x)
print("Точка b: ", y)
for i in range(n):
    sum+=pow(x1[i]-y1[i],2)
d = pow(sum,0.5)
print("Евклидово расстояние: ", d)


Точка а:  [77 29 27]
Точка b:  [16 95 77]
Евклидово расстояние:  102.84454287904633


2.3.2 Задание
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных

In [1]:
import pandas as pd
url = "https://gist.githubusercontent.com/jtbg/322083acb5da973ac288842a33400204/raw/c1a3fd2008a72b4f5e987b3a037c521f6587fb84/overwatch.csv"
data = pd.read_csv(url)
print(data)

   Minute (UTC)  Frontpage  r/Overwatch
0         22:00      53178         8711
1         22:01      52800         8814
2         22:02      53095         8839
3         22:03      52855         9315
4         22:04      52579         9582
..          ...        ...          ...
56        22:56      47626         8338
57        22:57      47546         7544
58        22:58      47905         7420
59        22:59      47873         7538
60        23:00      47865         7415

[61 rows x 3 columns]


2.3.3 Задание
Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7:
2.2.5 Пронализировать характеристики фрейма данных.
2.2.6 Выберите индивидуальные данные или срезы фрейма данных.
2.2.7 Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных.



In [1]:
import pandas as pd
url = "https://gist.githubusercontent.com/jtbg/322083acb5da973ac288842a33400204/raw/c1a3fd2008a72b4f5e987b3a037c521f6587fb84/overwatch.csv"
data = pd.read_csv(url)
print("Форма = ",data.shape)
print(data.describe())
print(data.iloc[30:40])
data[data['r/Overwatch']>12000].head(100)

C:\Users\borga\AppData\Local\Temp\ipykernel_6116\1531155567.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


Форма =  (61, 3)
          Frontpage   r/Overwatch
count     61.000000     61.000000
mean   51495.311475  33263.229508
std     1913.700434  32919.034247
min    47496.000000   7415.000000
25%    51283.000000   9537.000000
50%    52380.000000  12503.000000
75%    52800.000000  77682.000000
max    53663.000000  91034.000000
   Minute (UTC)  Frontpage  r/Overwatch
30        22:30      52818        23893
31        22:31      51557        36163
32        22:32      51969        65807
33        22:33      51662        77682
34        22:34      51305        85313
35        22:35      49883        82632
36        22:36      50529        82197
37        22:37      51158        85966
38        22:38      51283        87187
39        22:39      51888        88736


Minute (UTC)  Frontpage  r/Overwatch
19        22:19      52491        12040
20        22:20      52645        12503
21        22:21      53147        12456
22        22:22      52380        13204
23        22:23      52400        13696
24        22:24      52438        14430
25        22:25      52856        14745
26        22:26      53158        16099
27        22:27      52942        17756
28        22:28      53557        19771
29        22:29      52922        23530
30        22:30      52818        23893
31        22:31      51557        36163
32        22:32      51969        65807
33        22:33      51662        77682
34        22:34      51305        85313
35        22:35      49883        82632
36        22:36      50529        82197
37        22:37      51158        85966
38        22:38      51283        87187
39        22:39      51888        88736
40        22:40      51835        90549
41        22:41      52373        91034
42        22:42      52746        88255
43        22:43      53446        85105
44        22:44      53663        84173
45        22:45      52525        83635
46        22:46      52386        85273
47        22:47      51321        84555
48        22:48      52397        85635
49        22:49      49276        52648
50        22:50      48158        27541
51        22:51      48158        16711
52        22:52      47948        12412

3.3.2 Задание
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.


In [65]:
import pandas as pd
import statistics
import math
from sklearn.preprocessing import MinMaxScaler
url ='https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
df = pd.read_csv(url)
sred=sum(df['sepal_width_cm'])/df.shape[0] #Среднее арифметическое
otkl= sum((int(x) - sred) ** 2 for x in df['sepal_width_cm']) / (df.shape[0] - 1) #Среднее отклонение
min1=min(df['sepal_length_cm']) #Мин элемент
max1=max(df['sepal_length_cm']) #Макс элемент
#Scaler = MinMaxScaler()
#df[['sepal_length_cm']]=Scaler.fit_transform(df[['sepal_length_cm']])
#df
df[['sepal_length_cm']]=(df[['sepal_length_cm']]-min1)/(max1-min1)
#df[['sepal_width_cm']]=(df[['sepal_width_cm']]-df[['sepal_width_cm']].mean())/(df[['sepal_width_cm']].std())

df[['sepal_width_cm']]=(df[['sepal_width_cm']]-sred)/(otkl)
df

3.0540000000000007 0.45074765100671216
sepal_width_cm    3.054
dtype: float64 sepal_width_cm    0.433594
dtype: float64


sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.028611              1.4             0.2   
1           0.166667       -0.124540              1.4             0.2   
2           0.111111        0.336720              1.3             0.2   
3           0.083333        0.106090              1.5             0.2   
4           0.194444        1.259242              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124540              5.2             2.3   
146         0.555556       -1.277692              5.0             1.9   
147         0.611111       -0.124540              5.2             2.0   
148         0.527778        0.797981              5.4             2.3   
149         0.444444       -0.124540              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]